// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Data;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221208182607_InitializeMigrations")]
    partial class InitializeMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("src.Entities.BlogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PathToImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BlogEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7154),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img1.png}",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://notion.com"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7172),
                            Description = "If you’re well known in your region, the United States, or the world, you’ve likely put a lot of time and resources,,,",
                            PathToImage = "../../assets/images/blog_images/post_img1.png}",
                            Tag = "Reputation Management",
                            Title = "Why You Need An Online Reputation",
                            Url = "https://notion.com"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7173),
                            Description = "Fast People Search removal can help protect your privacy online. Learn how to complete the r/reddit.com ...",
                            PathToImage = "../../assets/images/blog_images/reddit.png",
                            Tag = "Social Media",
                            Title = "How to Remove Info from Reddit",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7175),
                            Description = "Since most customers will interact with as business for the first time on the internet, having an effective customer ....",
                            PathToImage = "../../assets/images/blog_images/headlines_img3.png",
                            Tag = "Reputation Management",
                            Title = "5 Strategies for Customer Review Management in 2022",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7176),
                            Description = "Having a great Google review management strategy is very important. They act as an icebreaker to....",
                            PathToImage = "../../assets/images/blog_images/privacy.png",
                            Tag = "Google Review",
                            Title = "How to Remove Personal Information from Google",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7223),
                            Description = "Fast People Search removal can help protect your privacy online. Learn how to complete the FastPeopleSearch...",
                            PathToImage = "../../assets/images/blog_images/hall.png",
                            Tag = "Politics",
                            Title = "Reputation Management for Politicians: What to Know",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7224),
                            Description = "Your public perception is known as your online reputation, telling others who you are, what …",
                            PathToImage = "../../assets/images/blog_images/post_img7.png",
                            Tag = "Reputation Management",
                            Title = "How to Remove My Information from Been Verified",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7225),
                            Description = "If you’re well known in your region, the United States, or the world, you’ve likely put a lot of time and...",
                            PathToImage = "../../assets/images/blog_images/headlines_img6.png",
                            Tag = "Reputation Management",
                            Title = "7 Software Development Models to Organize Your Team",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7226),
                            Description = "Your public perception is known as your online reputation, telling others who you are, what values...",
                            PathToImage = "../../assets/images/blog_images/headlines_img7.png",
                            Tag = "Social Media",
                            Title = "How to Remove My Information from Instagram",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7228),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img8.png",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7229),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img8.png",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7230),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img8.png",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7231),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img8.png",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://google.com"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 8, 19, 26, 7, 524, DateTimeKind.Local).AddTicks(7232),
                            Description = "Defamation removal can be challenging. With our step-by-step guide, learn how to protect ...",
                            PathToImage = "../../assets/images/blog_images/headlines_img8.png",
                            Tag = "Reputation Management",
                            Title = "How to Do Defamation Removal Online",
                            Url = "https://google.com"
                        });
                });

            modelBuilder.Entity("src.Entities.CareerResponse", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CoverLetterFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResumeFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("CareerResponses");
                });

            modelBuilder.Entity("src.Entities.ChallengeReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ComplaintMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ReviewId");

                    b.ToTable("challengeReviews");
                });

            modelBuilder.Entity("src.Entities.Quote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("src.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComplainerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LawyerEmail")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfReview")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ViewLastTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("src.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TrxRef")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("src.Entities.UserComplains", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ComplaintMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ComplaintId");

                    b.ToTable("UserComplaint");
                });
#pragma warning restore 612, 618
        }
    }
}
